CREATE DATABASE Const;
USE Const;

#UNIQUE VALUE
CREATE TABLE emp
( id INT UNIQUE
);
INSERT INTO emp VALUES(100);
INSERT INTO emp VALUES(101);

#show error duplicate value
#INSERT INTO Table1 VALUES(101);
SELECT * FROM emp1;

#NOT NULL VALUE
CREATE TABLE emp2
( id INT NOT NULL
);

INSERT INTO emp2 VALUES(200);
#INSERT INTO emp2 VALUES();
SELECT * FROM emp2;

#DEFAULT
CREATE TABLE emp3
( id INT,
  salary INT DEFAULT 25000
);
INSERT INTO emp3 (id,salary) VALUES(1,30000);
INSERT INTO emp3 (id) VALUES(2);
INSERT INTO emp3 (id) VALUES(3);

SELECT * FROM emp3;

#check 
CREATE TABLE City1
(
 id INT PRIMARY KEY,
 city VARCHAR(50),
 age INT,
CONSTRAINT age_CHECK  CHECK (age>=18)
);

INSERT INTO City1
	(id,city,age)
VALUES
	(121,"PUNE",19),
	(101,"Delhi",21);

SELECT * FROM City;

#PRIMARY KEY

CREATE TABLE STUD1
(
ID INT PRIMARY KEY,
NAME VARCHAR(80),
CITY_ID INT,
CITY_N VARCHAR(90),
FOREIGN KEY (CITY_ID) references C1 (ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO STUD1
	(ID,NAME,CITY_ID,CITY_N)
VALUES
		(1,"RAHUL",8,"DELHI"),
		(2,"KAMINI",1,"MUMBAI"),
		(3,"OMKAR",3,"PUNE"),
		(4,"VEDANT",1,"MUMBAI"),
		(5,"YOGESH",3,"PUNE");
        

		
SELECT * FROM STUD1;

CREATE TABLE C1
(
ID INT PRIMARY KEY,
CITY_N VARCHAR(90)
);

INSERT INTO C1
	(ID,CITY_N)
VALUES
	(1,"MUMBAI"),
    (2,"DELHI"),
    (3,"PUNE");
    
SELECT * FROM C1;
	



