CREATE DATABASE SUBQUERY;
USE SUBQUERY;

 CREATE TABLE STU11(
 ID INT PRIMARY KEY,
 NAME VARCHAR(50),
 MARKS INT NOT NULL
 );
 
 INSERT INTO STU11
	(ID ,NAME,MARKS)
 VALUES
	 (1,"ANUJA",89),
	 (2,"KAMINI",85),
	 (3,"PRACHI",90),
	 (4,"kUMKUM",92);
	 
 SELECT * FROM STU11;
 
SELECT NAME ,MARKS
FROM STU11
WHERE MARKS>(SELECT AVG(MARKS) FROM STU11);

SELECT MAX(MARKS)
FROM (SELECT * FROM STU11 WHERE NAME="ANUJA") AS TEMP;

SELECT ID,NAME
FROM STU11
WHERE ID IN(SELECT ID FROM STU11 WHERE ID%2=0);
 
 
