CREATE DATABASE SAMARTH;
USE SAMARTH;

CREATE TABLE TABLE1(
ID INT PRIMARY KEY,
NAME VARCHAR(60),
MARKS INT NOT NULL,
CITY VARCHAR(40),
GREAD VARCHAR(1)
);

INSERT INTO TABLE1
(ID,NAME ,MARKS,CITY,GREAD)
VALUES
#(101,"APEKSHA",91,"PUNE","A"),
#(102,"KAMINI",92,"DELHI","A");
#(103,"ANUJA",83,"PUNE","B");
(104,"ABHI",85,"NASHIK","B");

SET SQL_SAFE_UPDATES=0;
UPDATE TABLE1
SET GREAD="O"
WHERE GREAD="A";

#ADD COLUMN
ALTER TABLE TABLE1
ADD COLUMN AGE INT;

ALTER TABLE TABLE1
DROP COLUMN AGE;

#RENAME TABLE NAME
ALTER TABLE TABLE1
RENAME TO TABLE2;

SELECT * FROM TABLE2;